### PR TITLE
Export meshes to FBX and other small changes.

### PR DESCRIPTION
**Pull request by freezy**
Thanks to @jsm174 for figuring out how to make the damn FBX package work on Linux. I had to cheat a bit for the unit tests too, because somehow the geometry was slightly changed.

The other small change was fixing the locked hierarchy window in one of the provided layouts.

### CODE REVIEW

**Comment by jsm174** [comment]
> Thanks to @jsm174 for figuring out how to make the damn FBX package work on Linux. I had to cheat a bit for the unit tests too, because somehow the geometry was slightly changed.

Cool. Just for some notes incase we ever have to revisit this:

game-ci's test runner is currently built on Ubuntu 18.04. Out of the box, Ubuntu 18.04 has `libstdc++.so.6.0.25` installed.

According to: https://docs.unity3d.com/Packages/com.autodesk.fbx@4.1/manual/index.html, `libstdc++.so.6.0.28+` is required.

So as a work around, we need to temporarily use a custom game-ci unity test runner image base on Ubuntu 18 that has an upgraded libstdc++. When game-ci upgrades to Ubuntu 20, we can go back to official images.

To upgrade libstdc++, we made a custom Dockerfile:

```
FROM unityci/editor:2021.2.15f1-linux-il2cpp-0
RUN apt-get update && apt-get -y install software-properties-common && add-apt-repository -y ppa:ubuntu-toolchain-r/test && apt-get -y install --only-upgrade libstdc++6
```

```
docker build . -t jsm174/unityci_editor:2021.2.15f1-linux-il2cpp-0`
docker push jsm174/unityci_editor:2021.2.15f1-linux-il2cpp-0
```





This article was also helping in tracking this down:

https://forum.unity.com/threads/fbx-exporter-4-0-1-does-not-work-with-unity-2021-1-11-on-linux.1131481/

**Comment by jsm174** [comment]
> @jsm174 this is ready to merge now, right?

yes. In a future PR we will be able to remove the line: `customImage: 'unityci/editor:2021.2.16f1-linux-il2cpp-1'`. 

I believe `game-ci/unity-test-runner` needs to make a new release so it pulls its latest image.

**Comment by freezy** [comment]
Cool, can you watch this and update accordingly?

**Comment by jsm174** [comment]
@freezy - `unity-test-runner@main` was just updated to pull v1 images. (https://github.com/game-ci/unity-test-runner/pull/179)

This is good to merge now.

**Comment by freezy** [comment]
Awesome, thanks! 

But I wanted to fix colored material emission before merging. If I don't get to until tomorrow I'll merge nevertheless though.

**Pull request merged**
