### PR TITLE
Rubbers meshGen fix and Gizmo positioning fix for rubbers and MWG

### PR DESCRIPTION
**Pull request by Cupiii**
Fixes Issue "Rubbers do not colllide sometimes #377".

Wrote Rubbers from scratch (copied some code from MWG).

Also fixed UV Mapping

### CODE REVIEW

**Comment by freezy** [comment]
Cool! Is this something that could go back to VPX?

**Review by freezy — APPROVED** [review]
Very cool! There is a warning about `_middlePoint`, says it's never assigned but used. Can it be removed?

**Comment by Cupiii** [comment]
Have to look at it tomorrow.

**Comment by Cupiii** [comment]
_middlepoint is set again for rubbers and MWG. Test run fine on my computer.

**Comment by Cupiii** [comment]
Oh, and yes, that may be backported to VP as well, but check for MWG branch, where I edited something in SplineVertex class. I think I only made the 2d spline non loopable, but i may have altered more without knowing. I should have used the 3dSpline Class which was used for Ramps... but did not...

**Pull request merged**
