### PR TITLE
Add OSX support using NetMiniZ and updated NetVips

### PR DESCRIPTION
**Pull request by jsm174**
This PR will allow `VisualPinball.Engine` to be run on MacOS.

This PR has two parts:

1) Replace `MiniZ.Net` with `NetMiniZ` for `BiffZlib.cs`

I created `NetMiniZ` using the source code from `MiniZ.Net`. It was designed to be cross platform modeled after how `NetVips` works. Also `NetMiniZ` uses the latest `MiniZ 2.1.0`. All `NetMiniZ` native libraries were built and compiled using GitHub actions.

There are 3 NuGet packages:

https://www.nuget.org/packages/NetMiniZ/
https://www.nuget.org/packages/NetMiniZ.Native.osx-x64/
https://www.nuget.org/packages/NetMiniZ.Native.win-x64/

2) Update `NetVips` to `1.2.1` and include `NetVips.Native.osx-x64`

The build script was updated to copy the native libraries into the `Vendor` folder

`<BuildFiles Include="$(OutDir)*.dll;$(OutDir)*.xml;..\.packages\*\runtimes\win-x64\native\*.dll;..\.packages\*\runtimes\osx-x64\native\*.dylib" ... />`

Unfortunately `NetVips` on MacOS is not compiled into a single library, so many dependencies were added to the `Vendor` directory.

I believe this may change in the future as the author of `NetVips`, posted this:

https://github.com/lovell/sharp-libvips/issues/39#issuecomment-631345789

### CODE REVIEW

**Comment by freezy** [comment]
Hey, thanks a lot for this. (Windows) CI seems to fail though:

```
   VisualPinball.Engine.Test.VPT.TextureBitmapTests.ShouldAnalyzeATransparentTexture [FAIL]
      System.DllNotFoundException : Unable to load DLL 'libvips-42.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
      Stack Trace:
```

If you're willing to spend some time to setup GitHub actions for this, I'd be willing to switch. Unit tests for multiple platforms would be awesome.

**Comment by kleisauke** [comment]
> Unfortunately `NetVips` on MacOS is not compiled into a single library, so many dependencies were added to the `Vendor` directory.

fwiw, this is fixed with `v8.9.2-build2` which has just been released [on NuGet](https://www.nuget.org/packages/NetVips.Native/8.9.2-build2). 

Unfortunately, somehow NuGet sees this as a pre-release and indicates that the v8.9.2 is a newer version. :man_facepalming:

**Comment by freezy** [comment]
This PR is covered by #86 and can be closed, right?

**Comment by jsm174** [comment]
> This PR is covered by #86 and can be closed, right?

Correct, this PR was replaced by #83 and #86!

**Pull request closed without merging**
