### PR TITLE
Added support for x86 builds

### PR DESCRIPTION
**Pull request by jsm174**
This adds support for x86 builds.

1) NetVips automatically adds targets by looking for `MSBuildRuntimeType` and `$(OS)` variables. It doesn't automatically pull in the correct DLLs based on `Platform` (win) or `PlatformTarget` (x86/x64)

Screen Shot 2020-07-09 at 7 13 04 PM

2) NetMiniZ adds all the targets automatically since the x64 and x86 DLL have the same name, one of them will get copied over. 

So to get around any auto adding of any native libraries (which would normally get automatically copying to `VisualPinball.Engine.Test\.bin\Release`) , we explicitly exclude all assets:

```
    <PackageReference Include="NetMiniZ.Native" Version="1.0.4">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
    
    <PackageReference Include="NetVips.Native" Version="8.9.2-build3">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
```

Then when we are building the application we explicitly import the project for the machine it is being built on:

```
  <ImportGroup Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$(PlatformTarget)' == 'x86'">
    <Import Project="$(NuGetPackageRoot)\netminiz.native.win-x86\1.0.4\build\netstandard2.0\NetMiniZ.Native.win-x86.targets" Condition="Exists('$(NuGetPackageRoot)\netminiz.native.win-x86\1.0.4\build\netstandard2.0\NetMiniZ.Native.win-x86.targets')" />
    <Import Project="$(NuGetPackageRoot)\netvips.native.win-x86\8.9.2-build3\build\net45\NetVips.Native.win-x86.targets" Condition="Exists('$(NuGetPackageRoot)\netvips.native.win-x86\8.9.2-build3\build\net45\NetVips.Native.win-x86.targets')" />
  </ImportGroup>
  <ImportGroup Condition="$([MSBuild]::IsOSPlatform('Windows')) And '$(PlatformTarget)' != 'x86'">
    <Import Project="$(NuGetPackageRoot)\netminiz.native.win-x64\1.0.4\build\netstandard2.0\NetMiniZ.Native.win-x64.targets" Condition="Exists('$(NuGetPackageRoot)\netminiz.native.win-x64\1.0.4\build\netstandard2.0\NetMiniZ.Native.win-x64.targets')" />
```

By doing this approach, all nuget packages will still get downloaded, and we can continue to use our `VendorDeploy` step which copies everything to the Unity `Vendor` folder.

### CODE REVIEW

**Comment by freezy** [comment]
Looks good, thanks! Will work on getting the tests to pass. Do we need some kind of documentation how to upgrade any of the native dependencies? Like, which files to update rather than letting NuGet handle it and let it screw up everything?

**Comment by jsm174** [comment]
> Looks good, thanks! Will work on getting the tests to pass. Do we need some kind of documentation how to upgrade any of the native dependencies? Like, which files to update rather than letting NuGet handle it and let it screw up everything?

Sure. Where should we do that?

Basically any native DLLs, we'll need to manually update the `Import Project` entries because of the build numbers. 

`<Import Project="$(NuGetPackageRoot)\netvips.native.win-x86\8.9.2-build3\build\net45\NetVips.Native.win-x86.targets" Condition="Exists('$(NuGetPackageRoot)\netvips.native.win-x86\8.9.2-build3\build\net45\NetVips.Native.win-x86.targets')" />`

**Comment by freezy** [comment]
How about a Wiki page?

If you rebase to master (which builds now again), I'll have a look at the failing tests!

**Comment by jsm174** [comment]
> How about a Wiki page?
> 
> If you rebase to master (which builds now again), I'll have a look at the failing tests!

Done!

**Comment by freezy** [comment]
Awesome, runs fine now!

**Pull request merged**
